language: php

php:
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/phpunit/phpunit/phpunit tests/Unit --verbose
